### ISSUE TITLE
Kirby: Raise text block character limit

### ISSUE THREAD

**Issue by benjamindoubali** [vi-son/exhibition#9]
Current character limit for text blocks is 350. I think it's great to limit characters for a neat user experience and to limit ourselves, but maybe a doubled number of characters (700) are needed to develop a thought properly

**Comment by benjamindoubali** [comment]
Ok, the obviouss workaround is of course to add a second text block without a title - nevertheless, it's still cool to raise the character limit

**Comment by guidoschmidt** [comment]
Should be increased as discussed 🌚
